server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true

          routes:
            # ================= STUDENT SERVICE =================
            - id: student-service
              uri: lb://STUDENT-SERVICE
              predicates:
                - Path=/api/students/**
              filters:
                - StripPrefix=1

            - id: student-openapi
              uri: lb://STUDENT-SERVICE
              predicates:
                - Path=/student/v3/api-docs
              filters:
                - RewritePath=/student/(?<path>.*), /$\{path}

            # ================= SCHOOL SERVICE =================
            - id: school-service
              uri: lb://SCHOOL-SERVICE
              predicates:
                - Path=/api/schools/**
              filters:
                - StripPrefix=1

            - id: school-openapi
              uri: lb://SCHOOL-SERVICE
              predicates:
                - Path=/school/v3/api-docs
              filters:
                - RewritePath=/school/(?<path>.*), /$\{path}

springdoc:
  api-docs:
    enabled: false   # IMPORTANT : pas d'OpenAPI propre au Gateway
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Student Service
        url: /student/v3/api-docs
      - name: School Service
        url: /school/v3/api-docs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
