server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: student-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/students/**
        - id: school-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/schools/**

springdoc:
  api-docs:
    enabled: false   # IMPORTANT : pas d'OpenAPI propre au Gateway
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Student Service
        url: /student/v3/api-docs
      - name: School Service
        url: /school/v3/api-docs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
